---
version: "2"
services:
  heimdall:
    image: linuxserver/heimdall:2.2.2
    container_name: heimdall
    restart: unless-stopped
    
  overseerr:
    image: linuxserver/overseerr:1.28.0
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Specify a timezone to use
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /host/path/to/config:/config # Contains all relevant configuration files.
    ports:
      - 5055:5055/tcp # Web UI
    
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Configs/Organizr:/config
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=998
        - PGID=100
        - TZ=Europe/London
    
  qbittorrentvpn:
    image: chrisjohnson00/qbittorrent-openvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=//
      - VPN_PASSWORD=//
      - PUID=998
      - PGID=100
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
      - NAME_SERVERS=1.1.1.1 #you can use whatever DNS provider you want
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Configs/QBittorrentVPN:/config
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Torrents:/downloads
      - /etc/timezone:/etc/timezone:ro #This is for TimeZone
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Configs/Radarr:/config
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Downloads:/NZBdownloads
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Movies:/movies
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Configs/Sonarr:/config
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Downloads:/NZBdownloads
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/TvShows:/tv
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022
    volumes:
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Configs/Lidarr:/config
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Downloads:/NZBdownloads
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Music:/music
      - /srv/dev-disk-by-uuid-a55985e6-994d-496e-8779-4dbd3cbb2d51/Torrents:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
   
   plex:
    image: linuxserver/plex:1.25.4
    container_name: plex
    restart: unless-stopped
    
    

